### ISSUE TITLE
Magento 2.3 support

### ISSUE THREAD

**Issue by andrewkett** [section-io/magento-metrics#32]
Currently I cannot install this module with composer on Magento 2.2.3 due to the most recent magento/framework version not being supported in composer.json.

**Comment by niccolox** [comment]
thanks, Andrew for the bug report

**Comment by calvinbrewer** [comment]
Hey Andrew we've just updated the extension to support the magento/framework used in Magento 2.2.3 and above https://github.com/section-io/magento-metrics/pull/33
